import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/NavBar'
import GlobalState from '@/context'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <GlobalState>
          <NavBar />
          <main className="flex min-h-screen flex-col md:mt-[60px]">
            {children}
          </main>
        </GlobalState>
      </body>
    </html>
  )
}
